### ISSUE TITLE
[feat] 카드 등록 화면 구현

### ISSUE THREAD

**Issue by DONG-WOON** [ykm989/Cardfit#4]
1. OO카드 선택시 firestore에서 카드 DB 불러오기
2. 데이터 불러오기와 동시에 storage에서 카드 이미지 데이터도 함께 불러오기
3. OO카드 선택화면 구현
4. OO카드 리스트 화면으로 보여주기

**Comment by ykm989** [comment]
1. 불러온 데이터 기반으로 MainView에 연결
2. MainView 다듬기
3. Widget

**Comment by DONG-WOON** [comment]
1. OO카드 선택시 firestore에서 카드 DB 불러오기 (완료)
2. 데이터 불러오기와 동시에 storage에서 카드 이미지 데이터도 함께 불러오기 (완료)
3. OO카드 선택화면 구현 (진행중)
4. OO카드 리스트 화면으로 보여주기 (완료)

**Comment by DONG-WOON** [comment]
3. OO카드 선택화면 구현 (완료)
